---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 18/02/2023 22:23
---
local gfx <const> = playdate.graphics
local font <const> = gfx.getFont()
local gutter <const> = 4
local itemHeight = 20
local listY <const> = 18
local listRect <const> = playdate.geometry.rect.new(gutter, listY, 400 - 2*gutter, 240 - listY)
local listView = playdate.ui.gridview.new(0, itemHeight)
local viewModel
listView:setCellPadding(0, 0, gutter, gutter) -- left, right , top, bottom
listView:setScrollDuration(200)

class("FileSelectorView").extends()

function FileSelectorView:init(vm)
    FileSelectorView.super.init(self)
    self.initialRender = true
    viewModel = vm
    listView:setNumberOfRows(#viewModel.entries)
    listView:setSelectedRow(viewModel.selectedIdx)
    listView:scrollToRow(viewModel.selectedIdx, false)
end

function listView:drawCell(_, row, _, selected, x, y, width, height)
    local curOption = viewModel.entries[row]
    gfx.setColor(gfx.kColorBlack) -- shape color
    if selected then
        gfx.fillRoundRect(x, y, width, height, gutter)
        gfx.setColor(gfx.kColorWhite) -- shape color
    end
    gfx.setImageDrawMode(gfx.kDrawModeNXOR) --text color

    -- title
    font:drawText(curOption.path, x + gutter, y+gutter)
end

function FileSelectorView:resume()
    self.initialRender = true
end

function FileSelectorView:render()
    if self.initialRender then
        gfx.clear(gfx.kColorWhite)
    end

    -- header
    font:drawText(viewModel.title, 2,2)
    gfx.drawLine(0, listY-1, 400, listY-1)

    if listView:getSelectedRow() ~= viewModel.selectedIdx then
        listView:setSelectedRow(viewModel.selectedIdx)
        listView:scrollToRow(viewModel.selectedIdx)
    end

    local offsetRect = listRect:offsetBy(0,viewModel.listOffset)
    listView:drawInRect(offsetRect.x, offsetRect.y, offsetRect.width, offsetRect.height)

end
