---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 22/07/2022 17:05
---

local snd <const> = playdate.sound

--synths = {
--    snd.kWaveSine,
--    snd.kWaveSquare,
--    snd.kWaveSawtooth,
--    snd.kWaveTriangle,
--    snd.kWaveNoise,
--    snd.kWavePOPhase,
--    snd.kWavePODigital,
--    snd.kWavePOVosim,
--    "drums"
--}

synthNames = {
    [snd.kWaveSine] = "Sine",
    [snd.kWaveSquare] = "Square",
    [snd.kWaveSawtooth] = "Sawtooth",
    [snd.kWaveTriangle] = "Triangle",
    [snd.kWaveNoise] = "Noise",
    [snd.kWavePOPhase] = "POPhase",
    [snd.kWavePODigital] = "PODigital",
    [snd.kWavePOVosim] = "POVosim",
    drums = "Drums"
}
