---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 22/07/2022 14:45
---

local snd <const> = playdate.sound

function newsynth()
    local s = snd.synth.new(snd.kWaveSawtooth)
    s:setVolume(0.2)
    s:setAttack(0)
    s:setDecay(0.15)
    s:setSustain(0.2)
    s:setRelease(0)
    return s
end

function drumsynth(path)
    local sample = snd.sample.new(path)
    local s = snd.synth.new(sample)
    s:setVolume(0.5)
    return s
end

function newinst(n)
    local inst = snd.instrument.new()
    for _=1,n do
        inst:addVoice(newsynth())
    end
    return inst
end

function druminst()
    local inst = snd.instrument.new()
    inst:addVoice(drumsynth("drums/kick"), 35)
    inst:addVoice(drumsynth("drums/kick"), 36)
    inst:addVoice(drumsynth("drums/snare"), 38)
    inst:addVoice(drumsynth("drums/clap"), 39)
    inst:addVoice(drumsynth("drums/tom-low"), 41)
    inst:addVoice(drumsynth("drums/tom-low"), 43)
    inst:addVoice(drumsynth("drums/tom-mid"), 45)
    inst:addVoice(drumsynth("drums/tom-mid"), 47)
    inst:addVoice(drumsynth("drums/tom-hi"), 48)
    inst:addVoice(drumsynth("drums/tom-hi"), 50)
    inst:addVoice(drumsynth("drums/hh-closed"), 42)
    inst:addVoice(drumsynth("drums/hh-closed"), 44)
    inst:addVoice(drumsynth("drums/hh-open"), 46)
    inst:addVoice(drumsynth("drums/cymbal-crash"), 49)
    inst:addVoice(drumsynth("drums/cymbal-ride"), 51)
    inst:addVoice(drumsynth("drums/cowbell"), 56)
    inst:addVoice(drumsynth("drums/clav"), 75)
    return inst
end

function loadMidi(path)
    local s = snd.sequence.new(path)
    local ntracks = s:getTrackCount()
    local active = {}
    local poly = 0

    for i=1,ntracks do
        local track = s:getTrackAtIndex(i)
        if track ~= nil then
            local n = track:getPolyphony(i)
            if n > 0 then active[#active+1] = i end
            if n > poly then poly = n end
            print("track "..i.." has polyphony "..n)

            print("default instrument for track", i, track:getInstrument())

            if i == 10 then
                print("Creating Drums for track", i)
                track:setInstrument(druminst(n))
            else
                print("Creating Sawtooth for track", i)
                track:setInstrument(newinst(n))
            end
        end
    end

    return s
end
