---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 26/07/2022 21:59
---

local enum <const> = enum

tools = enum({
    "isSolo",
    "isMuted",
    "volume",
    "attack",
    "decay",
    "sustain",
    "release"
})
