---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 23/07/2022 12:48
---

function endsWith(str, ending)
    return ending == "" or str:sub(-#ending) == ending
end

function selectNext(tbl, current)
    local nextIndex = (lume.find(tbl, current) or 0) + 1
    if nextIndex > #tbl then
        nextIndex = 1
    end
    return tbl[nextIndex]
end
