---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 23/07/2022 12:48
---

local file <const> = playdate.file

function endsWith(str, ending)
    return ending == "" or str:sub(-#ending) == ending
end

function selectNext(tbl, current)
    local nextIndex = (lume.find(tbl, current) or 0) + 1
    if nextIndex > #tbl then
        nextIndex = 1
    end
    return tbl[nextIndex]
end

local function listFiles(path)
    if path then
        return file.listFiles(path)
    else
        return file.listFiles()
    end
end

--- provide null for all available data dirs
function listFilesRecursive(path)
    print("listrecursive ", path)
    local result = {}
    for _, item in ipairs(listFiles(path)) do
        local itemPath = (path or "") .. item
        print(itemPath)
        if file.isdir(itemPath) then
            print("--", itemPath)
            result = lume.merge(
                result,
                listFilesRecursive(itemPath)
            )
        else
            table.insert(result, (path or "") .. item)
        end
    end
    return result
end
