---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 22/07/2022 15:15
---

import "CoreLibs/object"

local justPressed <const> = playdate.buttonJustPressed
local justReleased <const> = playdate.buttonJustReleased
local buttonDown <const> = playdate.kButtonDown
local buttonUp <const> = playdate.kButtonUp
local buttonLeft <const> = playdate.kButtonLeft
local buttonRight <const> = playdate.kButtonRight
local buttonA <const> = playdate.kButtonA
local buttonB <const> = playdate.kButtonB

class("ViewModel").extends()

function ViewModel:init(sequence)
    self.sequence = sequence
    self.numTracks = sequence:getTrackCount()
    self.trackProps = {}
    for i = 1, self.numTracks do
        self.trackProps[i] = { muted = false }
    end
    self.selectedTrack = 1
end

function ViewModel:isMuted(trackNum)
    return self.trackProps[trackNum].isMuted
end

function ViewModel:update()
    if justPressed(buttonDown) and self.selectedTrack < self.numTracks then
        self.selectedTrack = self.selectedTrack + 1
    elseif justPressed(buttonUp) and self.selectedTrack > 1 then
        self.selectedTrack = self.selectedTrack - 1
    end
end
